[2024-03-18T06:40:30.175+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: two_separate_groups.format_to_parquet_dataset_3_task scheduled__2024-03-17T00:00:00+00:00 [queued]>
[2024-03-18T06:40:30.385+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: two_separate_groups.format_to_parquet_dataset_3_task scheduled__2024-03-17T00:00:00+00:00 [queued]>
[2024-03-18T06:40:30.396+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-18T06:40:30.622+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): format_to_parquet_dataset_3_task> on 2024-03-17 00:00:00+00:00
[2024-03-18T06:40:30.743+0000] {standard_task_runner.py:60} INFO - Started process 178 to run task
[2024-03-18T06:40:30.814+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'two_separate_groups', 'format_to_parquet_dataset_3_task', 'scheduled__2024-03-17T00:00:00+00:00', '--job-id', '194', '--raw', '--subdir', 'DAGS_FOLDER/ingest_data_to_gcs.py', '--cfg-path', '/tmp/tmpc0iud9i5']
[2024-03-18T06:40:30.834+0000] {standard_task_runner.py:88} INFO - Job 194: Subtask format_to_parquet_dataset_3_task
[2024-03-18T06:40:31.363+0000] {task_command.py:423} INFO - Running <TaskInstance: two_separate_groups.format_to_parquet_dataset_3_task scheduled__2024-03-17T00:00:00+00:00 [running]> on host 9958f290dc4a
[2024-03-18T06:40:33.582+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='two_separate_groups' AIRFLOW_CTX_TASK_ID='format_to_parquet_dataset_3_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-17T00:00:00+00:00'
[2024-03-18T06:40:33.598+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_data_to_gcs.py", line 38, in format_to_parquet
    table = pv.read_csv(src_file)
  File "pyarrow/_csv.pyx", line 1256, in pyarrow._csv.read_csv
  File "pyarrow/_csv.pyx", line 1115, in pyarrow._csv._get_reader
  File "pyarrow/io.pxi", line 2036, in pyarrow.lib.get_input_stream
  File "pyarrow/io.pxi", line 2007, in pyarrow.lib.get_native_file
  File "pyarrow/io.pxi", line 1134, in pyarrow.lib.OSFile.__cinit__
  File "pyarrow/io.pxi", line 1144, in pyarrow.lib.OSFile._open_readable
  File "pyarrow/error.pxi", line 154, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
FileNotFoundError: [Errno 2] Failed to open local file '/opt/airflow/chicago_crime_data_3.csv'. Detail: [errno 2] No such file or directory
[2024-03-18T06:40:33.767+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=two_separate_groups, task_id=format_to_parquet_dataset_3_task, execution_date=20240317T000000, start_date=20240318T064030, end_date=20240318T064033
[2024-03-18T06:40:33.982+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 194 for task format_to_parquet_dataset_3_task ([Errno 2] Failed to open local file '/opt/airflow/chicago_crime_data_3.csv'. Detail: [errno 2] No such file or directory; 178)
[2024-03-18T06:40:34.103+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-18T06:40:34.173+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
