[2024-03-14T11:13:36.309+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: two_separate_groups.delete_dataset_files_3_task scheduled__2024-03-13T00:00:00+00:00 [queued]>
[2024-03-14T11:13:36.355+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: two_separate_groups.delete_dataset_files_3_task scheduled__2024-03-13T00:00:00+00:00 [queued]>
[2024-03-14T11:13:36.358+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-14T11:13:36.396+0000] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): delete_dataset_files_3_task> on 2024-03-13 00:00:00+00:00
[2024-03-14T11:13:36.427+0000] {standard_task_runner.py:60} INFO - Started process 761 to run task
[2024-03-14T11:13:36.451+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'two_separate_groups', 'delete_dataset_files_3_task', 'scheduled__2024-03-13T00:00:00+00:00', '--job-id', '157', '--raw', '--subdir', 'DAGS_FOLDER/create_dag.py', '--cfg-path', '/tmp/tmpmvnp9hn0']
[2024-03-14T11:13:36.455+0000] {standard_task_runner.py:88} INFO - Job 157: Subtask delete_dataset_files_3_task
[2024-03-14T11:13:36.636+0000] {task_command.py:423} INFO - Running <TaskInstance: two_separate_groups.delete_dataset_files_3_task scheduled__2024-03-13T00:00:00+00:00 [running]> on host 9958f290dc4a
[2024-03-14T11:13:37.154+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='two_separate_groups' AIRFLOW_CTX_TASK_ID='delete_dataset_files_3_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-13T00:00:00+00:00'
[2024-03-14T11:13:37.163+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-14T11:13:37.170+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'rm -O /opt/***/chicago_crime_data_3.csv.gz             rm -O /opt/***/chicago_crime_data_3.parquet']
[2024-03-14T11:13:37.252+0000] {subprocess.py:86} INFO - Output:
[2024-03-14T11:13:37.268+0000] {subprocess.py:93} INFO - rm: invalid option -- 'O'
[2024-03-14T11:13:37.269+0000] {subprocess.py:93} INFO - Try 'rm --help' for more information.
[2024-03-14T11:13:37.273+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-03-14T11:13:37.304+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-03-14T11:13:37.314+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=two_separate_groups, task_id=delete_dataset_files_3_task, execution_date=20240313T000000, start_date=20240314T111336, end_date=20240314T111337
[2024-03-14T11:13:37.349+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 157 for task delete_dataset_files_3_task (Bash command failed. The command returned a non-zero exit code 1.; 761)
[2024-03-14T11:13:37.402+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-14T11:13:37.440+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
