[2024-03-26T16:34:31.770+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: data_crime_process_dag.download_connector_jar_task manual__2024-03-26T08:20:00.691315+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
