[2024-03-14T11:14:59.878+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: two_separate_groups.delete_dataset_files_1_task manual__2024-03-14T11:11:16.722311+00:00 [queued]>
[2024-03-14T11:14:59.897+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: two_separate_groups.delete_dataset_files_1_task manual__2024-03-14T11:11:16.722311+00:00 [queued]>
[2024-03-14T11:14:59.898+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-03-14T11:14:59.930+0000] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): delete_dataset_files_1_task> on 2024-03-14 11:11:16.722311+00:00
[2024-03-14T11:14:59.945+0000] {standard_task_runner.py:60} INFO - Started process 795 to run task
[2024-03-14T11:14:59.953+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'two_separate_groups', 'delete_dataset_files_1_task', 'manual__2024-03-14T11:11:16.722311+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/create_dag.py', '--cfg-path', '/tmp/tmpkquudu8s']
[2024-03-14T11:14:59.955+0000] {standard_task_runner.py:88} INFO - Job 161: Subtask delete_dataset_files_1_task
[2024-03-14T11:15:00.037+0000] {task_command.py:423} INFO - Running <TaskInstance: two_separate_groups.delete_dataset_files_1_task manual__2024-03-14T11:11:16.722311+00:00 [running]> on host 9958f290dc4a
[2024-03-14T11:15:00.178+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='two_separate_groups' AIRFLOW_CTX_TASK_ID='delete_dataset_files_1_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-14T11:11:16.722311+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-14T11:11:16.722311+00:00'
[2024-03-14T11:15:00.180+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-14T11:15:00.182+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'rm /opt/***/chicago_crime_data_1.csv             rm /opt/***/chicago_crime_data_1.parquet']
[2024-03-14T11:15:00.199+0000] {subprocess.py:86} INFO - Output:
[2024-03-14T11:15:00.211+0000] {subprocess.py:93} INFO - rm: cannot remove 'rm': No such file or directory
[2024-03-14T11:15:00.214+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-03-14T11:15:00.226+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-03-14T11:15:00.231+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=two_separate_groups, task_id=delete_dataset_files_1_task, execution_date=20240314T111116, start_date=20240314T111459, end_date=20240314T111500
[2024-03-14T11:15:00.252+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 161 for task delete_dataset_files_1_task (Bash command failed. The command returned a non-zero exit code 1.; 795)
[2024-03-14T11:15:00.289+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-14T11:15:00.312+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
