[2024-03-18T06:41:39.421+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: two_separate_groups.format_to_parquet_dataset_1_task manual__2024-03-18T06:40:31.356042+00:00 [queued]>
[2024-03-18T06:41:39.527+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: two_separate_groups.format_to_parquet_dataset_1_task manual__2024-03-18T06:40:31.356042+00:00 [queued]>
[2024-03-18T06:41:39.535+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-18T06:41:39.699+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): format_to_parquet_dataset_1_task> on 2024-03-18 06:40:31.356042+00:00
[2024-03-18T06:41:39.792+0000] {standard_task_runner.py:60} INFO - Started process 319 to run task
[2024-03-18T06:41:39.842+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'two_separate_groups', 'format_to_parquet_dataset_1_task', 'manual__2024-03-18T06:40:31.356042+00:00', '--job-id', '226', '--raw', '--subdir', 'DAGS_FOLDER/ingest_data_to_gcs.py', '--cfg-path', '/tmp/tmpolijpqwl']
[2024-03-18T06:41:39.877+0000] {standard_task_runner.py:88} INFO - Job 226: Subtask format_to_parquet_dataset_1_task
[2024-03-18T06:41:40.179+0000] {task_command.py:423} INFO - Running <TaskInstance: two_separate_groups.format_to_parquet_dataset_1_task manual__2024-03-18T06:40:31.356042+00:00 [running]> on host 9958f290dc4a
[2024-03-18T06:41:40.689+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='two_separate_groups' AIRFLOW_CTX_TASK_ID='format_to_parquet_dataset_1_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-18T06:40:31.356042+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-18T06:40:31.356042+00:00'
[2024-03-18T06:41:40.742+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_data_to_gcs.py", line 38, in format_to_parquet
    table = pv.read_csv(src_file)
  File "pyarrow/_csv.pyx", line 1261, in pyarrow._csv.read_csv
  File "pyarrow/_csv.pyx", line 1270, in pyarrow._csv.read_csv
  File "pyarrow/error.pxi", line 154, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: CSV parse error: Expected 30 columns, got 21: 11192453,JB100396,12/31/2017 11:55:00 AM,088XX S BISHOP ST,1310,CRIMINAL DAMAGE,TO PROPERTY,RESI ...
[2024-03-18T06:41:40.758+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=two_separate_groups, task_id=format_to_parquet_dataset_1_task, execution_date=20240318T064031, start_date=20240318T064139, end_date=20240318T064140
[2024-03-18T06:41:40.933+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 226 for task format_to_parquet_dataset_1_task (CSV parse error: Expected 30 columns, got 21: 11192453,JB100396,12/31/2017 11:55:00 AM,088XX S BISHOP ST,1310,CRIMINAL DAMAGE,TO PROPERTY,RESI ...; 319)
[2024-03-18T06:41:40.981+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-18T06:41:41.027+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
