[2024-03-28T07:32:28.678+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingesting_data_bq.format_to_parquet_dataset_4_task scheduled__2024-03-26T00:00:00+00:00 [queued]>
[2024-03-28T07:32:28.916+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingesting_data_bq.format_to_parquet_dataset_4_task scheduled__2024-03-26T00:00:00+00:00 [queued]>
[2024-03-28T07:32:28.921+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-28T07:32:29.192+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): format_to_parquet_dataset_4_task> on 2024-03-26 00:00:00+00:00
[2024-03-28T07:32:29.548+0000] {standard_task_runner.py:60} INFO - Started process 183 to run task
[2024-03-28T07:32:29.706+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ingesting_data_bq', 'format_to_parquet_dataset_4_task', 'scheduled__2024-03-26T00:00:00+00:00', '--job-id', '392', '--raw', '--subdir', 'DAGS_FOLDER/ingest_data_to_gcs.py', '--cfg-path', '/tmp/tmpi32xv30h']
[2024-03-28T07:32:29.746+0000] {standard_task_runner.py:88} INFO - Job 392: Subtask format_to_parquet_dataset_4_task
[2024-03-28T07:32:31.037+0000] {task_command.py:423} INFO - Running <TaskInstance: ingesting_data_bq.format_to_parquet_dataset_4_task scheduled__2024-03-26T00:00:00+00:00 [running]> on host d3d7fa608a49
[2024-03-28T07:32:33.298+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingesting_data_bq' AIRFLOW_CTX_TASK_ID='format_to_parquet_dataset_4_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-26T00:00:00+00:00'
[2024-03-28T07:32:33.566+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_data_to_gcs.py", line 37, in format_to_parquet
    table = pv.read_csv(src_file)
  File "pyarrow/_csv.pyx", line 1261, in pyarrow._csv.read_csv
  File "pyarrow/_csv.pyx", line 1270, in pyarrow._csv.read_csv
  File "pyarrow/error.pxi", line 154, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Empty CSV file
[2024-03-28T07:32:33.753+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=ingesting_data_bq, task_id=format_to_parquet_dataset_4_task, execution_date=20240326T000000, start_date=20240328T073228, end_date=20240328T073233
[2024-03-28T07:32:34.513+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 392 for task format_to_parquet_dataset_4_task (Empty CSV file; 183)
[2024-03-28T07:32:34.676+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-28T07:32:34.944+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
